---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes #Aqui é para o usuario vagrant virar root
  vars_files:
   - vars/main.yml
  vars:
   - dbname: "db01"
   - dbusername: "root"
   - dbpassword: "devopsmaonamassa"
  roles:
   - configuracao-default-so
   - role: geerlingguy.mysql
