# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "db01" #Atribuir nome ao servidor
  config.vm.network "private_network", ip: "192.168.1.4" #Atribuir ip virtual
  config.vm.network "forwarded_port", guest: 3306, host: 3306 #forward de porta 3306 é a porta padrao do MySql
  config.vm.provision "shell", path: "provision.sh"
end
